# Change these first
owner: nboxdev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Plex Server
    url: $SECRET_SITE001
  - name: Bazarr
    url: $SECRET_SITE002
  - name: Bazarr4K
    url: $SECRET_SITE003
  - name: Immich
    url: $SECRET_SITE004
  - name: Lavalink
    url: $SECRET_SITE005
    expectedStatusCodes:
      - 401
  - name: LibreSpeed
    url: $SECRET_SITE006
  - name: Memos
    url: $SECRET_SITE007
  - name: Notifiarr
    url: $SECRET_SITE008
  - name: Overseerr
    url: $SECRET_SITE021
  - name: Overseerr (Kids/Nordic)
    url: $SECRET_SITE022
  - name: Prowlarr
    url: $SECRET_SITE009
  - name: qBittorrent
    url: $SECRET_SITE010
  - name: Radarr
    url: $SECRET_SITE011
  - name: Radarr4K
    url: $SECRET_SITE012
  - name: Radarr (Kids/Nordic)
    url: $SECRET_SITE019
  - name: SABnzbd
    url: $SECRET_SITE013
  - name: Sonarr
    url: $SECRET_SITE014
  - name: Sonarr4K
    url: $SECRET_SITE015
  - name: Sonarr (Kids/Nordic)
    url: $SECRET_SITE020
  - name: Tautulli
    url: $SECRET_SITE016
  - name: Wizarr
    url: $SECRET_SITE017
  - name: Wrapperr
    url: $SECRET_SITE018

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.nbox.dev
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/gJLLHQE.png
  name: NBOX Uptime
  introTitle: "**NBOX Status Page**"
  introMessage: This is a simple status page for nbox.dev
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
